name: NPM Publish
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12.0.0
    - name: Setup NPM credentials
      run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - run: npm install
    - run: npm run build
    - name: Create Release Pull Request or Publish to npm
      id: changesets
      uses: changesets/action@master
      with:
        publish: npm publish
        commit: 'Bump up version'
        title: 'Upcoming Release Changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      
